---
- name: Copy sshd config
  become: true
  template: src=sshd_config.j2
            dest=/etc/ssh/sshd_config
            backup=yes
  register: sshd_config

- name: Restart SSH daemon
  become: true
  service: name=sshd
           state=restarted
           enabled=yes
  when: sshd_config.changed

- name: Generate iptables rule
  become: true
  template: src=iptables.j2
            dest=/etc/iptables

- name: Flush and apply new iptables rules
  become: true
  command: iptables-restore /etc/iptables

- name: Install Fail2Ban
  become: true
  apt:
    pkg: fail2ban
    update_cache: yes
    cache_valid_time: 3600
    state: latest

#- name: Configure Fail2Ban
#  become: true
#  template: src=jail.local.j2
#            dest=/etc/fail2ban/jail.local
#  register: jail_local

- name: Restart Fail2Ban
  become: true
  service: name=fail2ban
           state=restarted
           enabled=yes
#  when: jail_local.changed
